// <auto-generated />
namespace NTNB1721050329.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class crat_table_lecture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crat_table_lecture));
        
        string IMigrationMetadata.Id
        {
            get { return "202110260755356_crat_table_lecture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
